# -*- coding: utf-8 -*-
"""hi-net 데이터 npz 정리 추가 수정본.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/133RlRaFFsgR80IY0eMXyQpIdk_Oo23Ef
"""

!pip install obspy

from google.colab import drive
import obspy
import numpy as np
import os
import pandas as pd
from tqdm import tqdm

# 1. 구글 드라이브 마운트
drive.mount('/content/drive')

print("\n600초 윈도우(300초 오버랩) 슬라이싱 및 통합 npz 데이터셋 생성 시작...")

# 2. 파일 경로 설정
base_dir = "/content/drive/MyDrive/hi_net/hi-net_data"

mseed_file = os.path.join(base_dir, "tohoku_merged_45min.mseed")
pgv_csv_file = "/content/drive/MyDrive/hi_net/processed_pgv_data2.csv"
output_npz = os.path.join(base_dir, "tohoku_dataset_NEW2.npz")

# 3. PGV 데이터에서 타겟 관측소 목록 불러오기
df_pgv = pd.read_csv(pgv_csv_file)
valid_stations = set(df_pgv['station'].tolist())

# 4. 원본 지진파 데이터 불러오기
st = obspy.read(mseed_file)

# mseed에 실제로 저장된 관측소 이름들
mseed_stations_raw = list(set([tr.stats.station for tr in st]))

# 5. PGV, mssed 파일 관측소 자동 짝맞추기
pgv_to_mseed = {}

for pgv_sta in valid_stations:
    base_name = pgv_sta.replace('N.', '')[:-1]

    for m_sta in mseed_stations_raw:
        if base_name in m_sta:
            pgv_to_mseed[pgv_sta] = m_sta
            break

target_stations = sorted(list(pgv_to_mseed.keys()))
print(f"PGV 라벨 매칭이 완료된 슬라이싱 대상 관측소: {len(target_stations)}개")

TARGET_FS = 100
WIN_SEC = 600
STRIDE_SEC = 300

WIN = WIN_SEC * TARGET_FS       # 60,000
STRIDE = STRIDE_SEC * TARGET_FS # 30,000

all_windows = []
all_station_names = []
all_start_times = []

# 6. 관측소별 슬라이싱 진행
for target_sta in tqdm(target_stations, desc="관측소 데이터 처리 중"):
    actual_mseed_sta = pgv_to_mseed[target_sta]
    sta_st = st.select(station=actual_mseed_sta)

    if len(sta_st) < 3:
        continue

    try:
        tr_e = sta_st.select(component="E")[0]
        tr_n = sta_st.select(component="N")[0]
        tr_z_list = sta_st.select(component="U") or sta_st.select(component="Z")
        tr_z = tr_z_list[0]
    except IndexError:
        continue

    data_e, data_n, data_z = tr_e.data, tr_n.data, tr_z.data
    min_len = min(len(data_e), len(data_n), len(data_z))

    # 윈도우 크기(600초)보다 짧은 데이터는 스킵
    if min_len < WIN:
        continue

    # 해당 관측소 지진파 기록의 절대 시작 시각 가져오기
    start_utc = tr_e.stats.starttime

    data_matrix = np.column_stack((data_e[:min_len], data_n[:min_len], data_z[:min_len]))

    # 600초 간격, 300초 겹치게 슬라이싱
    starts = range(0, min_len - WIN + 1, STRIDE)
    windows = np.stack([data_matrix[s:s+WIN] for s in starts], axis=0)
    num_windows = len(windows)

    # Z-score 정규화
    mean = np.mean(windows, axis=1, keepdims=True)
    std = np.std(windows, axis=1, keepdims=True)
    std[std == 0] = 1e-8
    normalized_windows = (windows - mean) / std

    all_windows.append(normalized_windows)

    # 관측소 이름 추가
    all_station_names.extend([target_sta] * num_windows)

    # 각 윈도우 조각의 UTC 시작 시간 기록
    window_times = [str(start_utc + (s / TARGET_FS)) for s in starts]
    all_start_times.extend(window_times)

# 7. 최종 텐서, 이름표, 타임스탬프 배열을 하나의 .npz 파일로 통합 저장
if all_windows:
    print("\n잘라낸 조각들을 하나로 결합 중...")

    final_dataset = np.vstack(all_windows)
    final_names = np.array(all_station_names)
    final_times = np.array(all_start_times)

    np.savez_compressed(output_npz, data=final_dataset, station_names=final_names, start_times=final_times)

    print(f"\n[전처리 완료]")
    print(f"하나의 통합 파일로 저장되었습니다: {output_npz}")
    print(f"- 포함된 파형 데이터 형태: {final_dataset.shape} (기대값: N, 60000, 3)")
    print(f"- 포함된 관측소 이름 형태: {final_names.shape}")
    print(f"- 포함된 윈도우 시간 형태: {final_times.shape}")
else:
    print("\n조건에 맞는 3채널 데이터가 없습니다.")