from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] 

#top-level folders
DATA = ROOT / "data"
PREPROCESSING = ROOT / "preprocessing"
WORK = ROOT / "work"

#data base
RAW = DATA / "raw"
PROCESSED = DATA / "processed"
CSV = DATA / "csv"
POST = DATA / "postprocessing"

#modalities
RAW_GNSS = RAW / "gnss"
RAW_SEIS = RAW / "seismic"

PROC_GNSS = PROCESSED / "gnss"
PROC_SEIS = PROCESSED / "seismic"
PROC_PGV = PROCESSED / "pgv"

CSV_GNSS = CSV / "gnss"
CSV_SEIS = CSV / "seismic"
CSV_SAMPLES = CSV / "samples"
CSV_PAIRS = CSV / "station_pairs"

#events
TOHOKU = "tohoku"
NOTO = "noto"
KUMAMOTO = "kumamoto"

# ---- GNSS: tohoku ----
GNSS_TOHOKU_RAW = RAW_GNSS / TOHOKU
GNSS_TOHOKU_PROC = PROC_GNSS / TOHOKU
GNSS_TOHOKU_CSV = CSV_GNSS / TOHOKU

GNSS_NOTO_RAW = RAW_GNSS / NOTO
GNSS_NOTO_PROC = PROC_GNSS / NOTO
GNSS_NOTO_CSV = CSV_GNSS / NOTO

GNSS_KUMAMOTO_RAW = RAW_GNSS / KUMAMOTO
GNSS_KUMAMOTO_PROC = PROC_GNSS / KUMAMOTO
GNSS_KUMAMOTO_CSV = CSV_GNSS / KUMAMOTO

# ---- SEISMIC: tohoku ----
SEIS_TOHOKU_RAW = RAW_SEIS / TOHOKU
SEIS_TOHOKU_PROC = PROC_SEIS / TOHOKU
SEIS_TOHOKU_CSV = CSV_SEIS / TOHOKU

SEIS_NOTO_RAW = RAW_SEIS / NOTO
SEIS_NOTO_PROC = PROC_SEIS / NOTO
SEIS_NOTO_CSV = CSV_SEIS / NOTO

# ---- Station pairs ----
PAIRS_TOHOKU_CSV = CSV_PAIRS / TOHOKU
PAIRS_NOTO_CSV = CSV_PAIRS / NOTO

# ---- PGV ----
PGV_TOHOKU = PROC_PGV / TOHOKU
PGV_NOTO = PROC_PGV / NOTO

CROSS_EVENT = "cross-event"

GNSS_CROSS = PROC_GNSS / CROSS_EVENT